language: php

matrix:
    include:
        - php: 5.6
        - php: 7.0
        - php: 7.1
        - php: 7.2
        - php: 7.3
        - php: nightly
    allow_failure:
        - php: nightly

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install

script: vendor/bin/phpunit
